### ISSUE TITLE
remove GITHUB_PAT requirement

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#102]
- [ ] ~depends on https://github.com/RMI-PACTA/pacta.scenario.preparation/issues/123~
- [ ] depends on https://github.com/RMI-PACTA/pacta.data.preparation/issues/283
- [ ] depends on https://github.com/RMI-PACTA/workflow.scenario.preparation/issues/10
- [ ] depends on https://github.com/RMI-PACTA/workflow.scenario.preparation/issues/9
- [ ] depends on https://github.com/RMI-PACTA/pacta.scenario.data.preparation/issues/12

Currently a GITHUB_PAT environment variable is required for the Docker context in order to install [RMI-PACTA/pacta.scenario.preparation](https://github.com/RMI-PACTA/pacta.scenario.preparation) and [RMI-PACTA/pacta.data.preparation](https://github.com/RMI-PACTA/pacta.data.preparation). If both of those packages ever become public, it would be advantageous to remove that requirement.

changes would be needed here:

https://github.com/RMI-PACTA/workflow.data.preparation/blob/c08b8fb5a139716997ae2c0e83a01757d51a9a2d/README.md?plain=1#L39

https://github.com/RMI-PACTA/workflow.data.preparation/blob/c08b8fb5a139716997ae2c0e83a01757d51a9a2d/README.md?plain=1#L49-L51

[AB#10386](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10386)

**Comment by jdhoffa** [comment]
Relates to https://github.com/RMI-PACTA/pacta.scenario.data.preparation/issues/2

**Comment by cjyetman** [comment]
I guess this would not be needed anymore too, because in this context it's only used to make GITHUB_PAT available for the R pkgs install. @jdhoffa do you agree?

https://github.com/RMI-PACTA/workflow.data.preparation/blob/c08b8fb5a139716997ae2c0e83a01757d51a9a2d/Dockerfile#L20

**Comment by cjyetman** [comment]
also relates to #3

**Comment by jdhoffa** [comment]
Comment updated with additional context relating to:

https://github.com/RMI-PACTA/workflow.scenario.preparation
and
https://github.com/RMI-PACTA/pacta.scenario.data.preparation

**Comment by AlexAxthelm** [comment]
@cjyetman @jdhoffa I think this was closed with #217, no?
