### ISSUE TITLE
consider using a base image that has an arm64 version available

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#104]
Somewhat oddly, [`rocker/tidyverse`](https://hub.docker.com/r/rocker/tidyverse/tags) does not have an arm64 version available while [`rocker/rstudio`](https://hub.docker.com/r/rocker/rstudio/tags) does. Switching to `rocker/rstudio` (and removing or parameterizing the platform specification `--platform=linux/amd64`) would allow drastically increased performance on arm64 machines, though in this particular comparison some tidyverse packages would need to be installed during the image build process which are currently included "for free" with `rocker/tidyverse`.

https://github.com/RMI-PACTA/workflow.data.preparation/blob/c08b8fb5a139716997ae2c0e83a01757d51a9a2d/Dockerfile#L1

related #95

**Comment by jdhoffa** [comment]
Gonna dump some thoughts that are absolutely out of scope for this particular issue... happy to transfer it to somewhere else that makes more sense, but it covers quite a lot of topics...

but we may consider going back to what we did once upon a time, and maintaining our own (small) ecosystem of Docker images (based on `ubuntu` probably to start with, and maybe even `alpine` one day if we think that's useful...)

Something that we had started here:
https://github.com/RMI-PACTA/docker

I think splitting up Docker images as we had before seems to make sense:
* system deps
* R packages
* `pacta.*` packages

could( strong could) be a cool idea... 

Pros I see here, are that all sys deps are just handled once and in one place (probably would make the `Dockerfile` in every `workflow.*` wayyyy more simple... we could just call `FROM pacta-docker:v20240209` at the beginning and then `Run main.R` or whatever...

That `pacta.*` docker image could/ might be used to ensure that whatever `workflow.data.prep`, `workflow.pacta`, `workflow.pacta.report` etc. is built using the exact same `pacta.*` packages (dictated by the `pacta-docker` version)

Could even simplify our "release" strategy as "update the `pacta.*` docker image every quarter?

I really haven't thought about this a lot, so I guess there probably are down-sides too but ¯\_(ツ)_/¯ !

cc @AlexAxthelm

**Comment by AlexAxthelm** [comment]
I think that `workflow.pacta` makes sense as base for most of the images we build. Everything else (`workflow.factset`, `workflow.data.prep`) is going to be different enough that trying to keep deps/sysdeps in sync is probably going to be more trouble than it's worth. 

Overall, I'm of a mind to just add _only_ what's needed for each image, rather than trying to maintain a common "core" image that can be used in a lot of circumstances. Keeping it more isolated helps keeps the blast radius when something goes wrong smaller.

**Comment by AlexAxthelm** [comment]
But overall, exploring a base image that has an `arm64` version available readily seems like a reasonable thing to look into when we get a minute.

**Comment by AlexAxthelm** [comment]
> Somewhat oddly, [rocker/tidyverse](https://hub.docker.com/r/rocker/tidyverse/tags) does not have an arm64 version available while [rocker/rstudio](https://hub.docker.com/r/rocker/rstudio/tags) does

I wonder if this is because there aren't `tidyverse` arm64 versions available readily, and to keep the build times down, they aren't building those (`stringr` in particular is a _long_ build). the `tidyverse` image [builds on](https://rocker-project.org/images/) the `rstudio` one.

Overall, I would suggest exploring in the other direction, since [`r-ver`](https://hub.docker.com/r/rocker/r-ver/tags) does have `arm64` versions available on dockerhub.

**Comment by jdhoffa** [comment]
> Overall, I'm of a mind to just add _only_ what's needed for each image, rather than trying to maintain a common "core" image that can be used in a lot of circumstances. Keeping it more isolated helps keeps the blast radius when something goes wrong smaller.

yup totally fair, as I said just a bit of brain dump, not sold on the idea.
NIT: coding is always the same "should this be a module" question we ask ourselves 200 times a day, just with different hats on lol

**Comment by cjyetman** [comment]
I agree that there would be some benefit to this, but I also vaguely remember the experience of building out https://github.com/RMI-PACTA/docker and maintaining it and iirc the experience was mostly negative and what drove us to eventually just use a pre-rolled image that at least has R installed. I could maybe dig into the history of that to better remember/understand why it was a pain to inform this discussion.

**Comment by cjyetman** [comment]
> I wonder if this is because there aren't `tidyverse` arm64 versions available readily, and to keep the build times down, they aren't building those (`stringr` in particular is a _long_ build). the `tidyverse` image [builds on](https://rocker-project.org/images/) the `rstudio` one.

likely, though arm64 binaries are easily available now on Posit Package Manager. Rocker probably has not moved on that yet.

> Overall, I would suggest exploring in the other direction, since [`r-ver`](https://hub.docker.com/r/rocker/r-ver/tags) does have `arm64` versions available on dockerhub.

I'm also inclined toward that
