### ISSUE TITLE
use Posit Package Manager for faster binary installs in Docker

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#114]
Setting `https://packagemanager.posit.co/cran/__linux__/focal/latest` as the default CRAN repo will allow the R package installs in Docker to be much faster since it provides binaries for Linux.

⚠️ However, currently arm64 binaries are only available for Debian.

**Comment by jdhoffa** [comment]
Is this interesting also for https://github.com/RMI-PACTA/workflow.transition.monitor and friends?

**Comment by cjyetman** [comment]
already used in workflow.transition.monitor
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/main/Dockerfile#L29-L30

**Comment by jdhoffa** [comment]
Woops! Didn't even look, sorry

**Comment by cjyetman** [comment]
tagging as blocked in consideration that #112 may soon be merged making this a non-optimal change

**Comment by AlexAxthelm** [comment]
the Rocker images are all Debian, aren't they?

**Comment by cjyetman** [comment]
> the Rocker images are all Debian, aren't they?

yes, you're right (I think)
https://rocker-project.org/images/

weird, I think I got confused because workflow.transition.monitor uses
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/db0c750aee92d17ddc94a2762821ef4980d9f17e/Dockerfile#L29
```Dockerfile
ARG CRAN_REPO="https://packagemanager.posit.co/cran/__linux__/jammy/2023-10-30"
```
but also based on rocker 🤔

**Comment by AlexAxthelm** [comment]
I'm guessing they're calling it by the Ubuntu name 22.04 - Jammy Jellyfish, which is a derivative of Debian 11 (Bookworm).

**Comment by AlexAxthelm** [comment]
Oh, I had it backwards. the R versioned stack (including `r-ver`) is based on `ubuntu`, but the `r-base` stack builds on debian. 

https://rocker-project.org/images/

**Comment by cjyetman** [comment]
> > the Rocker images are all Debian, aren't they?
> 
> yes, you're right (I think) https://rocker-project.org/images/

actually, it's mixed...

for rocker/r-ver and those that build on it...
> This stack builds on stable Debian releases (for R versions <= 3.6.3) or Ubuntu LTS (for R versions >= 4.0.0).

for rocker/r-base and those that build on it...
> This stack builds on debian:testing and Debian unstable repo. Use this stack if you want access to the latest versions of system libraries and compilers through apt-get.

**Comment by AlexAxthelm** [comment]
Different issue though, why are we using `latest`, rather than date pinning?

**Comment by cjyetman** [comment]
> Different issue though, why are we using `latest`, rather than date pinning?

🤷🏻 @jdhoffa created the Dockerfile in this repo

but to be fair... I am less concerned about package versions in this repo than I am in the TM repo

**Comment by jdhoffa** [comment]
answer is: I made it `latest` and never changed it.

I see no problem with yall pinning it to whatever you wish :-)
