### ISSUE TITLE
add checks for valid config paramaters

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#118]
Numerous parameters are read in through the config file (see below). While the file paths/names are ultimately tested for existence, there are no basic validity checks on the parameters, e.g. checks that necessary parameters exist, that parameters are not `NULL`, that parameters are not `""`, and/or that parameter values are within a set of valid values. This could be achieved in the [run_pacta_data_preparation.R](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/run_pacta_data_preparation.R) script, or more (maybe better?) it could be achieved through a set of validation functions added in [pacta.data.preparation](https://github.com/RMI-PACTA/pacta.data.preparation).

https://github.com/RMI-PACTA/workflow.data.preparation/blob/a349890cab43dea90bc3f20cdf33a7cf6c8fc0c3/run_pacta_data_preparation.R#L20-L59

**Comment by AlexAxthelm** [comment]
@cjyetman, you're basically looking for checks on the config, where it would be something along the lines of:

```r
#ugly code
if (
  isnull(config$asset_impact_data_path) || 
  config$asset_impact_data_path == "" || 
  !dir.exists(config$asset_impact_data_path) 
) {
  stop("some message")
}
```

There isn't anything inherently wrong with this approach, but it's going to get messy to maintain. 

I really think this might be time to look at a different mechanism for managing our configs. I know I've pitched JSON Schema as a cure for a lot of our problems before, but this kind of validation is exactly what it's built for.

consider this snippet, which would handle those checks (from the current `main` in workflow.pacta, with only the `jsonvalidate::` line added

```r
logger::log_trace("Determining configuration file path")
cfg_path <- commandArgs(trailingOnly = TRUE)
if (length(cfg_path) == 0 || cfg_path == "") {
  logger::log_warn("No configuration file specified, using default")
  cfg_path <- "input_dir/default_config.json"
}
logger::log_debug("Loading configuration from file: \"{cfg_path}\".")
jsonvalidate::(cfg_path, schema_path) # this is the new line
cfg <- fromJSON(cfg_path)
```

then the same code from above would be

```jsonc
{
// ... json schema preamble
  "type": "object"
  "properties": {
    "asset_impact_data_path": {
      "description": "path to raw data files from Asset Impact. See README for more information."
      "type": "string"
      "regex": "[^\0]+" // not a great regex, but at least flags illegal characters in a POSIX path.
    },
    //... another example
    "sector_list": { // Define an array (vector) of objects, with permitted values in a predefined list.
      "description": "list of sectors available for use in PACTA dataset",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Steel", "Power", "Shipping", "O&G"]
      }
    }
  }
}

**Comment by cjyetman** [comment]
I already started implementing one method of doing this in pacta.data.preparation and reviewed with @jdhoffa and we strongly disagreed and where it was done, how it was down, what it checked or it didn't check, etc. and what @AlexAxthelm is proposing is also something completely different. So I think for now I'm going to table this idea. At some point we'll have to figure out how to focus on getting more done and less debate about micro differences about how to do them.

In any case, I think validating most of these config options is over-engineering anyway. The filepaths (for which there is already some form of checking in place) make sense because there's an expectation that these filepaths will be modified frequently depending on what context this is running in. The rest of the options, by design, should only be modified *very rarely* and only under strict scrutiny with well-defined justification, i.e. in a PR.
