### ISSUE TITLE
Explore if `fs::file_exists()` is more convenient for checking data path existence in main `run_pacta_data_preparation.R`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.data.preparation#119]
Consider if the `file.exists()` checks in [run_pacta_data_preparation.R](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/run_pacta_data_preparation.R) can be improved to take into account the possibility of the paths specifying a directory instead of a file.

related #118

https://github.com/RMI-PACTA/workflow.data.preparation/blob/0dc1012c2bcb5ada8990877a4860aa1d2f58a69c/run_pacta_data_preparation.R#L106-L121

originally from @jdhoffa 

> Have you checked if this problem persists using functions from https://fs.r-lib.org/ ?
> 
> I know there's a hesitance to add dependencies which I totally understand but given that this repository is concerned primarily with file I/O, I don't think depending on a package that facilitates better file I/O in R is a terrible idea 
> 
> _Originally posted by @jdhoffa in https://github.com/RMI-PACTA/workflow.data.preparation/pull/99#issuecomment-1936963999_

**Comment by cjyetman** [comment]
For reference, the documentation of `fs::dir_exists()` is here: https://fs.r-lib.org/reference/file_access.html

Currently, the base R equivalent `dir.exists()` is not used anywhere in this repo. This could be relevant to #118 if it was determined that the need to check for directory existence was needed.

**Comment by jdhoffa** [comment]
Title updated.

**Comment by cjyetman** [comment]
Generally, these are the primary differences between functions in `fs` and base R equivalents, according to the maintainers of `fs`

https://github.com/r-lib/fs?tab=readme-ov-file#comparison-vs-base-equivalents

> ## Comparison vs base equivalents
> 
> **fs** functions smooth over some of the idiosyncrasies of file handling
> with base R functions:
> 
> - Vectorization. All **fs** functions are vectorized, accepting multiple
>   paths as input. Base functions are inconsistently vectorized.
> 
> - Predictable return values that always convey a path. All **fs**
>   functions return a character vector of paths, a named integer or a
>   logical vector, where the names give the paths. Base return values are
>   more varied: they are often logical or contain error codes which
>   require downstream processing.
> 
> - Explicit failure. If **fs** operations fail, they throw an error. Base
>   functions tend to generate a warning and a system dependent error
>   code. This makes it easy to miss a failure.
> 
> - UTF-8 all the things. **fs** functions always convert input paths to
>   UTF-8 and return results as UTF-8. This gives you path encoding
>   consistency across OSes. Base functions rely on the native system
>   encoding.
> 
> - Naming convention. **fs** functions use a consistent naming
>   convention. Because base R’s functions were gradually added over time
>   there are a number of different conventions used (e.g. `path.expand()`
>   vs `normalizePath()`; `Sys.chmod()` vs `file.access()`).

I am also aware of another significant difference: that the way `fs` functions deal with `~` on Windows is more consistent.

Specifically to the context that was discussed in #99, the `fs` equivalent functions have the same behavior...
``` r
dir_name <- "~/Desktop/"

isTRUE(file.exists(file.path(dir_name, "dataprep")))
#> [1] TRUE
isTRUE(file.exists(file.path(dir_name, "FOO")))
#> [1] FALSE
isTRUE(file.exists(file.path(dir_name, "")))
#> [1] TRUE
isTRUE(file.exists(file.path(dir_name, NULL)))
#> [1] FALSE


isTRUE(fs::file_exists(file.path(dir_name, "dataprep")))
#> [1] TRUE
isTRUE(fs::file_exists(file.path(dir_name, "FOO")))
#> [1] FALSE
isTRUE(fs::file_exists(file.path(dir_name, "")))
#> [1] TRUE
isTRUE(fs::file_exists(file.path(dir_name, NULL)))
#> [1] FALSE

isTRUE(fs::file_exists(fs::path(dir_name, "dataprep")))
#> [1] TRUE
isTRUE(fs::file_exists(fs::path(dir_name, "FOO")))
#> [1] FALSE
isTRUE(fs::file_exists(fs::path(dir_name, "")))
#> [1] TRUE
isTRUE(fs::file_exists(fs::path(dir_name, NULL)))
#> [1] FALSE
```

**Comment by jdhoffa** [comment]
👌

**Comment by cjyetman** [comment]
re-opening with a renewed focus on the `file.exists()` checks in [run_pacta_data_preparation.R](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/run_pacta_data_preparation.R)

**Comment by AlexAxthelm** [comment]
I'd like to flag this for further investigation. I've had issues with the `fs` copy functions when using an SMB mount for Azure File Shares (errors, not warnings), and have been preferring the `base` functions in my code since then out of an abundance of caution. I'm open to trying the `fs` functions again, but I'd like to ensure that they'll work in our target environment.

I don't expect the `_exists` functions to cause problems, but before we go too far down this path, it's worth checking.

**Comment by cjyetman** [comment]
Since there are concerns with both `fs::file_exists()` and `base::file.exists()`, I lean towards "don't fix what ain't broke". closing
