### ISSUE TITLE
consider using imported parameters directly from the `config` object, rather than copying them to global environment

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#160]
Currently, parameters imported from the [`config.yml`](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/config.yml) are copied into global variables one-by-one [here](https://github.com/RMI-PACTA/workflow.data.preparation/blob/e27b2d443a6322874d4883187275cd41bf6b30cd/run_pacta_data_preparation.R#L34-L65), and then used via these global variables. It may be preferable to access the parameters directly from the `config` object rather than creating numerous global variables. e.g.

change this...
```r
data_prep_outputs_path <- config$data_prep_outputs_path

...

currencies_data_path <- file.path(data_prep_outputs_path, "currencies.rds")
```

to this...
```r
currencies_data_path <- file.path(config[["data_prep_outputs_path"]], "currencies.rds")
```

**Comment by AlexAxthelm** [comment]
I'm all for this. Noting that where we currently do the conversion from config elements to top-level R objects (`x <- config$x`) should be replaced with a check that the elements we are using exist in the config, as a way to preserve fail-fast behavior

```r
expected_keys <- c(
  "asset_impact_data_path",
  "factset_data_path",
  "data_prep_outputs_path",
  ...
)
stopifnot(all(expected_keys %in% names(config)))
```
