### ISSUE TITLE
consider merging `zero_emission_factor_techs` and `green_techs`

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#165]
Configs currently contain both `zero_emission_factor_techs` and `green_techs`, but they both ostensibly mean the same thing.

`zero_emission_factor_techs` is used as an input to `pacta.data.preparation::prepare_masterdata()` [here](https://github.com/RMI-PACTA/workflow.data.preparation/blob/f46e3ea578b65ce2045d568f23e76516d7f824a5/run_pacta_data_preparation.R#L366-L370) and [here](https://github.com/RMI-PACTA/workflow.data.preparation/blob/f46e3ea578b65ce2045d568f23e76516d7f824a5/run_pacta_data_preparation.R#L388-L392).

`green_techs` is used as an input to `pacta.scenario.preparation::format_p4i()` [here](https://github.com/RMI-PACTA/workflow.data.preparation/blob/f46e3ea578b65ce2045d568f23e76516d7f824a5/run_pacta_data_preparation.R#L264).

[`pacta.scenario.preparation::format_p4i()`](https://github.com/RMI-PACTA/pacta.data.preparation/blob/main/R/prepare_masterdata.R) uses `zero_emission_factor_techs` as
> A character vector listing technologies that will have emission factors manually forced to 0

[`pacta.scenario.preparation::format_p4i()`](https://github.com/RMI-PACTA/pacta.scenario.preparation/blob/main/R/format_p4i.R) uses `green_techs` as
> A list of green technologies. For these, a `direction` of "increasing" will be assigned, and the `smsp` column will be used to assign a `fair_share_perc`. Otherwise the `direction` will be `decreasing` and the `tmsr` column will be used.

It's possible that these lists could be merged and/or should be aligned. @jdhoffa

**Comment by jdhoffa** [comment]
I do not believe these should be aligned. These variables represent different information. For example, sometimes `GasCap` has been an `increasing` technology, however, it is certainly not zero emission. 

I would recommend closing this issue.
