### ISSUE TITLE
Don't write to file system root in docker image

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.data.preparation#172]
As a matter of practice, we should avoid writing to the file system root (`/`), and instead create application-specific directories (which may be at root) to isolate code and make inheriting images easier.

**Comment by cjyetman** [comment]
I think this is resolved by #175 @AlexAxthelm?

**Comment by AlexAxthelm** [comment]
> I think this is resolved by #175 @AlexAxthelm?

Agreed. Marking as closed.
