### ISSUE TITLE
reconsider the 2023Q4 parameters once they have been thoroughly investigated

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#176]
#136 added the 2023Q4 config under time pressure with inadequate validation of the parameters. Once they have been thoroughly validated, we should update the config with the most correct values we can figure out.

[AB#10387](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10387)

**Comment by jdhoffa** [comment]
For posterity regarding scenarios:
* Decision over what scenarios to include for PACTA COP CH 2024 can be found here: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/9975#30492700
* Decisions made by Nicholas Dodd
* Scenarios to include are: `isf_2023`, `geco_2023`, `weo_2023`
* Expected sectors by scenario are:
ISF 2023: `c( "Cement", "Coal", "Oil&Gas", "Power", "Steel")`
WEO 2023 `c("Automotive", "Aviation", "Cement", "Coal", "Oil&Gas", "Power", "Steel")`
GECO 2023 `c("Aviation", "Coal", "Oil&Gas", "Power", "Steel")`
* **OF NOTE**: GECO pending data questions regarding "Automotive" prevented it from being included in scenario preparation. This is considered BLOCKED until further inspection by analyst team. It sounds like this is something that will be explored later for a `GENERAL` release

Things that were flagged on Teams and ADO but may not have been formally addresse:
* While some of these scenarios contain more regional pathways, only "Global" appears on the final report. Something to potentially look into for `GENERAL`.
* Uncertain if/ how the more regional pathways affect the GlobalAggregate calculations...

**Comment by cjyetman** [comment]
actually, decision for scenarios is supposed to be here, no?
https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/9355/

**Comment by jdhoffa** [comment]
I'm not sure where it is "supposed to be", I'm just saying where it is haha.

I had a call to solicit scenario decisions and documented all decisions as a comment, tagging all involved in the call.
The result of that can be found here:
https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/9975#30492700

Maybe a good idea to also add it to the ticket you linked?

**Comment by jdhoffa** [comment]
I've added a comment to a similar effect there with the latest verbal decisions that I have a record of from the last "Scenario Decision Making" call

**Comment by cjyetman** [comment]
Not to be nit-picky, but I'd really like us to have a well-defined place where it is "supposed" to be recorded so that it's easy to go back to and verify if needed. Comments in various threads have, in the past, conflicted with each other, so I think it's advantageous to have one fixed, agreed place where the decision is made clear. (thanks for your effort towards that @jdhoffa)

**Comment by cjyetman** [comment]
@jdhoffa says (in the ADO ticket) that the 2023Q4 parameters have been thoroughly reviewed and verified.... closing
