### ISSUE TITLE
integrate the indices prep process

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#2]
For PACTA inputs to be fully ready to use, the indices portfolios need to be run through PACTA using the new data prepared by data.prep. That has been done in the past with [RMI-PACTA/workflow.prepare.pacta.indices](https://github.com/RMI-PACTA/workflow.prepare.pacta.indices). It would be advantageous to integrate that process here, so it can all be done in one workflow, in the proper order.

@jdhoffa @AlexAxthelm

**Comment by jdhoffa** [comment]
Yeah I back this. 

Since `pacta.data.preparation` and `pacta.portfolio.analysis` are totally separate packages, I think it makes sense to have a workflow that depends on both of them.

**Comment by cjyetman** [comment]
Given the discussion here https://github.com/RMI-PACTA/pacta.data.preparation/issues/278 I think we're leaning towards keeping separate `workflow.data.preparation` and `workflow.prepare.pacta.indices` because the output of `workflow.data.preparation` *without the indices/benchmark result files* has legitimate purpose/use, so it's plausible that we would want to run `workflow.data.preparation` but not run `workflow.prepare.pacta.indices`. Therefore, I'm closing this issue because it's contrary to the current strategy.
