### ISSUE TITLE
consider creating a GH action that can run this workflow with mock data

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#6]
it would be ideal to have some automated CI running here

**Comment by jdhoffa** [comment]
Let's make a friggin mock data repo!!!!! that would be a huge immediate gain IMO
@fariiaakh @AlexAxthelm

**Comment by fariiaakh** [comment]
A mock data repo that creates mock data?

**Comment by jdhoffa** [comment]
Indeed! Similar to: https://github.com/RMI-PACTA/r2dii.data
But for `pacta.data.preparation` inputs

(Alternatively we can potentially bundle it in with `pacta.data.preparation`, I just envision a future where we may want the mock data in another context)

**Comment by cjyetman** [comment]
hopefully the repo is not "mock" and just the data is 😆

**Comment by jdhoffa** [comment]
^ Agree

**Comment by cjyetman** [comment]
tagging this as blocked until such mock data exists (which is arguably much more difficult than creating the GH action that would use it)

**Comment by cjyetman** [comment]
Once pacta.data.preparation is public (https://github.com/RMI-PACTA/pacta.data.preparation/issues/283), I think we will move towards a GH action that runs this with *real* data, in which case this issue will be no longer relevant? @jdhoffa

**Comment by AlexAxthelm** [comment]
I think this remains relevant, since the "mock data" version is then effectively part of our public documentation / quickstart guide

**Comment by jdhoffa** [comment]
Yeah definitely agreed, template data is very useful in any case IMO

**Comment by AlexAxthelm** [comment]
I think that would be the right call

**Comment by cjyetman** [comment]
hmmm.... I think the thing that creates something should document what it creates, rather than all the things that use it.

**Comment by jdhoffa** [comment]
I agree with @AlexAxthelm on this one, the package should clearly document/ mock its inputs. 

If you have a function `f(x) -> y`, and a mocked input `x`, you can easily determine `y`. 
If on the other hand, you document the outputs, then you have `y` and the function `f(x)`, but you can't (easily) determine `x`.

**Comment by cjyetman** [comment]
closing in favor of #190
