### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#64]
The README has a few things that seem to be out of sync with the current code:
1. `HOST_INPUTS_PATH` and `HOST_OUTPUTS_PATH` env vars from the `.env` file do not appear to be used at all, instead those values are taken from the config file https://github.com/RMI-PACTA/workflow.data.preparation/blob/86881db2d3e8b1141697ec2a82ed5e2bef3f6e09/run_pacta_data_preparation.R#L33-L34
2. `GITHUB_PAT` doesn't seem to be needed/used at all. It seems like the code expects the necessary pkgs to be installed already https://github.com/RMI-PACTA/workflow.data.preparation/blob/86881db2d3e8b1141697ec2a82ed5e2bef3f6e09/run_pacta_data_preparation.R#L4-L6

**Comment by jdhoffa** [comment]
> 

Actually, `HOST_INPUTS_PATH` and `HOST_OUTPUTS_PATH` are still used in the `.env` file as these define the source inputs and output paths which are then mounted into the docker container. These would be something like `home/azureuser/AR_2022Q4` for example. 

The `config$data_prep_inputs_path` etc. are used to define the destination mounting paths in the docker container. These would be something like `/inputs` for example.

**Comment by jdhoffa** [comment]
And `GITHUB_PAT` is still used as well. 

The `.env` file is read into the docker image here: 
https://github.com/RMI-PACTA/workflow.data.preparation/blob/86881db2d3e8b1141697ec2a82ed5e2bef3f6e09/Dockerfile#L20

The PAT is then automatically used by `pak` to install the private repos `pacta.scenario.preparation` and `pacta.data.preparation` here:
https://github.com/RMI-PACTA/workflow.data.preparation/blob/86881db2d3e8b1141697ec2a82ed5e2bef3f6e09/Dockerfile#L21C2-L21C2

**Comment by jdhoffa** [comment]
I have made some very slight adjustments to the readme, to make it more clear with that `HOST_*_PATH` arguments should be set to, but otherwise the `README` is totally up to date.

**Comment by cjyetman** [comment]
OK, I was confused once again because I don't typically use Docker and I was trying to step through some of the process to fix another issue, and what happens when you run this code directly is different than what happens when you run it in Docker. That seems like some kinda confusion we should try to smooth out eventually.

**Comment by jdhoffa** [comment]
I think the mental model to assume would be that ONCE you are in the docker container, you should expect the behaviour to work similarly as your local machine. 

So like volume mounting, and installing dependencies etc. is a `Docker` specific process, but once the container is set-up, then there should be a parallel between that container and however you want to step through the process locally

**Comment by cjyetman** [comment]
My mental model is that the code and documentation should work, whether or not it is in a Docker container. To me the Docker setup is a convenience for running the process, but running the code locally in RStudio not in a Docker container is very helpful when debugging/coding/etc. I understand now that the README reflects how it works when one runs it in a Docker container, but I believe it would be advantageous to find a way for the code and documentation to be in sync and be relevant whether or not one is running it in a Docker container, because one of the primary maintainers of this repo frequently hacks on this code outside of a Docker container.
