### ISSUE TITLE
add relevant instructions to README for running locally

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#67]
The current README is relevant if one is using Docker and the [docker-compose.yml](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/docker-compose.yml) to set mounted directories correctly inside the container, but if one is not using Docker to run the script the instructions in the current README are not relevant.

I propose that we create a new section in the README with relevant instructions for running locally and clearly identify each section e.g. "Docker instructions" and "Local instructions".

**Comment by jdhoffa** [comment]
Perhaps beyond just "create instructions", I might scope this issue further as "develop and maintain a good process for" running data prep locally/ using RStudio. Not sure if the workflow is optimized in that way currently.
