### ISSUE TITLE
remove no longer necessary install of Chrome and its dependencies

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#91]
https://github.com/RMI-PACTA/workflow.data.preparation/blob/7a9a3b5b65c235e1a880ffcdeb744ec6c860677a/Dockerfile#L3-L11

@jdhoffa I believe this was added in #43 solely to support using `pacta.data.scraping::get_index_regions()`, which used to depend on {chromate} which depends on having an available Chrome or Chromium installation. Since https://github.com/RMI-PACTA/pacta.data.scraping/pull/20 changed the dependency from {chromate} to {V8}, I believe this could be removed.

**Comment by jdhoffa** [comment]
XD I have no idea what/ if this is necessary! but if it is only for `chromote` as you suggest, then this sounds reasonable

**Comment by jdhoffa** [comment]
Am I assigned on purpose? Would you expect me to open a PR relating to this?

**Comment by cjyetman** [comment]
not really, I can do it. Just looking for your verification that switching to V8 removed this dependency, which I thought was the driver for https://github.com/RMI-PACTA/pacta.data.scraping/pull/20. I think I was on PTO when that happened.

**Comment by AlexAxthelm** [comment]
I would love to drop this dependency.

**Comment by cjyetman** [comment]
also a kind of soft experiment with what it's like to have someone else be a codeowner in a repo that I maintain

**Comment by jdhoffa** [comment]
I confirm that `pacta.data.scraping` no longer depends on `chromote`.

I cannot confirm that the lines in the `Dockerfile` you link are exclusively related to `chromote`. But if you are confident of that, then I would back removing it!

**Comment by jdhoffa** [comment]
> also a kind of soft experiment with what it's like to have someone else be a codeowner in a repo that I maintain

Not to be pedantic, but you are the only `CODEOWNER` in this repository? (currently) 
https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/.github/CODEOWNERS

**Comment by cjyetman** [comment]
> Not to be pedantic, but you are the only `CODEOWNER` in this repository? (currently) https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/.github/CODEOWNERS

that's why I called it a "soft experiment", meaning not fully the case but kinda gives the experiment

**Comment by jdhoffa** [comment]
got it.

**Comment by cjyetman** [comment]
> I confirm that `pacta.data.scraping` no longer depends on `chromote`.
> 
> I cannot confirm that the lines in the `Dockerfile` you link are exclusively related to `chromote`. But if you are confident of that, then I would back removing it!

Since, in my memory, you were the one that primarily drove the development of the Dockerfile (starting when it lived in pacta.data.preparation), and since I can't effectively run it so I have very little knowledge or experience with it....

do you have any viable suggestion for the conundrum that this is probably a reasonable change to make but neither of us feel comfortable making that call?

**Comment by AlexAxthelm** [comment]
In the mean time, this probably can be assigned to me. I remember the process failing when I tried to take that section out (which is why it's in its own section on the ACI branch) https://github.com/RMI-PACTA/workflow.data.preparation/blob/5feeef1fe9aebc5d50e9259a7c402d1433767b46/ACI/Dockerfile.ACI#L25-L29

but that might have been written before before we switched to `V8`. I can investigate.

**Comment by jdhoffa** [comment]
FYI. I think https://github.com/RMI-PACTA/workflow.data.preparation/issues/94 would get us to the situation that:
@cjyetman can feasibly maintain `pacta.data.preparation` exclusively
@AlexAxthelm can feasibly maintain `workflow.data.preparation` exclusively 

Which could help remove the need to have "different maintainers for different parts of a repo"

**Comment by jdhoffa** [comment]
Anyway, don't want to distract from this issue. 
What is proposed here sounds reasonable to me!! I trust you two to do it without breaking anything XD
