### ISSUE TITLE
Consider using `alpine` OR  an LTS version of `ubuntu` as a base image for the `Dockerfile`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.data.preparation#95]
@AlexAxthelm FYI

**Comment by AlexAxthelm** [comment]
Do we have a `long-term` label? I think this is a fine idea, but the rocker images are working fine right now.

**Comment by cjyetman** [comment]
`long-term` label created and assigned (also `potentially dangerous` is assigned)

**Comment by cjyetman** [comment]
Current Dockerfile uses `rocker/tidyverse` as a base
https://github.com/RMI-PACTA/workflow.data.preparation/blob/3f453857a853fad313b4ace041a18107b6fd1e63/Dockerfile#L1


`rocker/tidyverse` uses `rocker/r-ver` as a base
https://rocker-project.org/images/versioned/rstudio.html#overview

> These images are based on [rocker/r-ver](https://rocker-project.org/images/versioned/r-ver.html), and [RStudio Server](https://www.rstudio.com/products/rstudio/download-server/) is already installed.


which uses Ubuntu LTS as a base
https://rocker-project.org/images/versioned/r-ver.html#overview
> rocker/r-ver is alternate image to [r-base](https://hub.docker.com/_/r-base), with an emphasis on reproducibility.
> 
> Compared to r-base,
> 
> Builds on Ubuntu LTS rather than Debian and system libraries are tied to the Ubuntu version. Images will use the most recent LTS available at the time when the corresponding R version was released.
> Since compatibility problems are likely to occur immediately after the release of a new Ubuntu LTS, the version to be used is the one that is at least 90 days past release.
> rocker/r-ver:4.0.0 is based on Ubuntu 20.04 (ubuntu:focal) because no interval was set at the time of the Ubuntu 20.04 release.
> Installs a fixed version of R itself from source, rather than whatever is already packaged for Ubuntu (the r-base stack gets the latest R version as a binary from Debian unstable).

---

Additionally, any change in base image would have to justify the advantages, while outweighing the advantage of having all the {tidyverse} packages already installed.
